name:                ham-asm
version:             0.1.0.0
github:              "nam3less/ham-asm"
license:             BSD3
author:              "Robin Beckmann"
maintainer:          "robin.m.beckmann@gmail.com"
copyright:           "2020 Robin Beckmann"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Assembler for HAM-ASM
# category:            Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nam3less/ham-asm#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 8.0.0 && < 9
- text
- containers
- optparse-applicative

library:
  source-dirs: src
  ghc-options:
  - -Wall
  default-extensions:
    - OverloadedStrings

executables:
  ham-asm:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -static
    - -optc-static
    - -optl-static
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    default-extensions:
      - OverloadedStrings
    dependencies:
    - ham-asm
  ham-asm-static:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -static
    - -optc-static
    - -optl-static
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    default-extensions:
      - OverloadedStrings
    dependencies:
    - ham-asm

tests:
  ham-asm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ham-asm
