name:                ham-asm
version:             0.1.0.0
github:              "nam3less/ham-asm"
license:             bsd3
author:              "Robin Beckmann"
maintainer:          "robin.m.beckmann@gmail.com"
copyright:           "2020 Robin Beckmann"

extra-source-files:
- readme.md
- changelog.md

# metadata used when publishing your package
# synopsis:            short description of your package
# category:            web

# to avoid duplicated efforts in documentation and dealing with the
# complications of embedding haddock markup inside cabal files, it is
# common to point users to the readme.md file.
description:         please see the readme on github at <https://github.com/nam3less/ham-asm#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 8.0.0 && < 9
- text
- containers
- optparse-applicative

library:
  source-dirs: src
  ghc-options:
  - -wall
  default-extensions:
    - overloadedstrings

executables:
  ham-asm:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -static
    - -threaded
    - -rtsopts
    - -with-rtsopts=-n
    - -wall
    default-extensions:
      - overloadedstrings
    dependencies:
    - ham-asm

tests:
  ham-asm-test:
    main:                spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-n
    dependencies:
    - ham-asm
